console.log('dari master')
console.log('dari master')
console.log('dari master')
console.log('dari master')
console.log('dari master')

console.log('AG-1')
console.log('AG-1')
console.log('AG-1')
console.log('AG-1')